controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
        
ruestzeit:
    path:       /{ruestzeit_id}
    controller: App\Controller\RuestzeitController::show
