controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
        
ruestzeit:
    path:       /{ruestzeit_id}
    controller: App\Controller\RuestzeitController::show

pageNotFound:
    path:  /{path}
    defaults: { _controller: App\Controller\PageNotFoundController::not_found_redirect, path: '' }
    requirements:
        path: .*